version: '3.9'

services:
  blazor-app:
    image: adriangs1996/blazor-app
    build: 
      context: .
      dockerfile: ./AppDockerfile
    ports:
      - "8000:5010"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVER_API=http://net6-api:8000/
      - ASPNETCORE_URLS=http://0.0.0.0:5010
      - NOTIFICATION_HUB=http://blazor-app:5010/notifications
  
  net6-api:
    image: adriangs1996/net6-api
    build:
      context: .
      dockerfile: ./ApiDockerfile
    ports:
      - "5000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://net6-api:8000/