version: '3.9'

services:
  blazor-app:
    image: adriangs1996/blazor-app
    build: 
      context: .
      dockerfile: ./AppDockerfile
    ports:
      - "8080:443"
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=secret
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./TestClientBlazor/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
  
  net6-api:
    image: adriangs1996/net6-api
    build:
      context: .
      dockerfile: ./ApiDockerfile
    ports:
      - "8000:8000"